# Generated by Django 5.1.7 on 2025-04-01 04:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CalorieEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("food_name", models.CharField(max_length=255)),
                ("calories", models.PositiveIntegerField()),
                ("date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
